[package]
name = "survey-redirect"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
axum = "0.6.20"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
chrono = "0.4.31"
config = "0.13.4"
parking_lot = { version = "0.12.1", features = ["hardware-lock-elision"] }
rand = "0.8.5"
serde = "1.0.193"
serde_json = "1.0.108"
tempfile = "3.8.1"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread", "fs", "io-util", "parking_lot"] }
tower-http = { version = "0.4.0", features = ["auth"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
url = { version = "2.4.1", features = ["serde"] }
