version: 2.1

jobs:
  build:
    parameters:
      os:
        type: string
    docker:
      - image: congyuwang/rust-container:llvm17-stable-1.77.0-<< parameters.os >>
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cargo build --release
            mv ./target/release/survey-redirect ./target/release/survey-redirect-x86_64-<< parameters.os >>
      - run:
          name: "Install python3"
          command: |
            apt update
            apt install python3 python3-pip -y
            pip3 install requests tqdm
      - run:
          name: "Test"
          command: |
            python3 tests.py
      - store_artifacts:
          name: "Save Binary"
          path: ./target/release/survey-redirect-x86_64-<< parameters.os >>
          destination: survey-redirect-x86_64-<< parameters.os >>

workflows:
  build-binary:
    jobs:
      - build:
          matrix:
            parameters:
              os: ["jammy", "focal", "debian-10", "debian-11"]
