version: 2.1

jobs:
  build:
    parameters:
      os:
        type: string
    docker:
      - image: congyuwang/socket-manager-dev:<< parameters.os >>
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cargo build --release
            mv ./build/survey_redirect ./build/survey_redirect-x86_64-<< parameters.os >>
      - store_artifacts:
          name: "Save Binary"
          path: ./build/survey_redirect-x86_64-<< parameters.os >>
          destination: survey_redirect-x86_64-<< parameters.os >>
      - persist_to_workspace:
          root: ./build
          paths:
            - survey_redirect-x86_64-<< parameters.os >>

workflows:
  build-binary:
    jobs:
      - build:
          matrix:
            parameters:
              os: ["jammy", "focal", "debian-10", "debian-11"]
